# Generated by Django 4.2.3 on 2023-11-30 06:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_userprofile_delete_userprofiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_id',
            field=models.UUIDField(default=uuid.UUID('5210df3a-c9e8-49ca-be46-1e76c89605df'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
